name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  package-and-publish:
    name: Package and Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run PyInstaller
        run: python -m PyInstaller --onefile main.py --name 'Break Scheduler' --icon=breakScheduler.ico
      
      - name: Get Latest Release
        id: latest_release
        uses: jossef/action-latest-release-info@v1.2.2
      
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with: 
          upload_url: ${{ steps.latest_release.outputs.upload_url }}
          asset_path: ./dist/BreakScheduler