name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  package-and-publish-windows:
    name: Package and Publish - Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run PyInstaller
        run: python -m PyInstaller --onefile main.py --name 'BreakScheduler' --icon=breakScheduler.ico --noconsole
      
      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/BreakScheduler.exe

  package-and-publish-ubuntu:
    name: Package and Publish - Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run PyInstaller
        run: python -m PyInstaller --onefile main.py --name 'BreakScheduler' --noconsole
      
      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/BreakScheduler